### ISSUE TITLE
Active pill offset and color do not work.

### ISSUE THREAD

**Issue by zexy72** [dhruv8sh/plasma6-desktopindicator-gnome#2]
The newly added setting does not work as intended.
![ginti](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/76520434/3cfe105a-c26d-4d64-976c-1f70132dc8c3)

As it can be, custom settings have been applied but there are no changes.

Distro: OpenSuse Tumbleweed
Linux: 6.8.1
Plasma: 6.0.3

**Comment by dhruv8sh** [comment]
It's working for me. Can you try restarting the plasma shell and maybe putting offset to a higher value?

**Comment by zexy72** [comment]
Plasma reload is needed for changes to load every time and is not changed on the fly like previous settings.
Custom color seems to be working fine but adding offset moved the pill up.

![ginti2](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/76520434/86a8faeb-9448-471f-a792-65a8ab4d0dc2)

![ginti3](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/76520434/44907eee-28a4-4458-ab26-33589a4f228b)

offset in wrong axis?

**Comment by dhruv8sh** [comment]
It's a one line fix but I am not home currently. It will be fixed when I do go home. You can temporarily fix this just by simply changing the active desktop.

**Comment by zexy72** [comment]
Looks like this after changing desktop
![ginti4](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/76520434/8cdaa42a-b2f7-457f-a56e-64b05e814dd3)

**Comment by dhruv8sh** [comment]
It is supposed to look like this. The height of the active indicator is offset with respect to the inactive indicators by the value.

**Comment by zexy72** [comment]
Shouldn't the length of the active pill be offset or is it because of vertical desktops?

**Comment by dhruv8sh** [comment]
Nah. I'm working on horizontal offset. 
The applet has to do some really janky stuff to get everything right. Hence, it's taking me longer to implement it.
(Also, I completely forgot how Gnome shows its indicator so I accidentally added a vertical offset.)

**Comment by dhruv8sh** [comment]
The latest commit fixes this. The release would be tomorrow when I apply a couple more things.

**Comment by zexy72** [comment]
Is the update available in pling? The offset is still vertical and not horizontal.

**Comment by dhruv8sh** [comment]
Currently it is not. The fix introduced a minor animation bug, which most people won't notice too much. But I intend on solving it before I publish the release.

**Comment by dhruv8sh** [comment]
Fixed!
