### ISSUE TITLE
It crashes my desktop when I try to place it

### ISSUE THREAD

**Issue by IOplus** [dhruv8sh/plasma6-desktopindicator-gnome#3]
For some reason it crashes my desktop when I try to place it. I'll attach a log from the crash, maybe it helps.

Applet: v0.5
Distro: Fedora 40
Linux: 6.8.5
Plasma: 6.0.3
Graphics Platform: Wayland
Graphics Processor: NVIDIA GeForce RTX 3060

[plasmashell-20240421-183635.kcrash.log](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/files/15059030/plasmashell-20240421-183635.kcrash.log)

**Comment by dhruv8sh** [comment]
Can you run ```plasmashell --replace```.
Add the plasmoid to your desktop after it. And paste the logs it presents after adding it?

**Comment by IOplus** [comment]
It prints this in the terminal:
```
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:196:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
file:///home/issa20omais/.local/share/plasma/wallpapers/a2n.blur/contents/ui/main.qml:84:21: QML QQuickImage: Cannot open: file:///usr/share/wallpapers/Mountain/
file:///home/issa20omais/.local/share/plasma/wallpapers/a2n.blur/contents/ui/main.qml:19:1: QML WallpaperItem: grabToImage: item's window is not visible
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:162:21: QML KSortFilterProxyModel: Binding loop detected for property "sourceModel"
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:162:21: QML KSortFilterProxyModel: Binding loop detected for property "sourceModel"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/ThumbnailStrip.qml"
qt.dbus.integration: Could not connect "org.cups.cupsd.Notifier" to PrinterFinishingsChanged(QString, QString, QString, uint, QString, bool) : 
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0

org.kde.pim.akonadiserver: New notification connection (registered as Akonadi::Server::NotificationSubscriber(0x7f18341fd650) )
org.kde.pim.akonadiserver: Subscriber Akonadi::Server::NotificationSubscriber(0x7f18341fd650) identified as "PlasmaEventModelMonitor - 94481297954272"
<Unknown File>: QML QQuickAnchors: Binding loop detected for property "bottomMargin"
<Unknown File>: QML QQuickAnchors: Binding loop detected for property "bottomMargin"
<Unknown File>: QML QQuickAnchors: Binding loop detected for property "bottomMargin"
<Unknown File>: QML QQuickAnchors: Binding loop detected for property "bottomMargin"

org.kde.pim.akonadiserver: Handler exception when handling command FetchItems on connection plasmashell-1310126243 (0x557a8a4d5700) : Operations based on remote identifiers require a resource or collection context
org.kde.pim.akonadiserver: Handler exception when handling command FetchItems on connection plasmashell-1310126243 (0x557a8a4d5700) : Operations based on remote identifiers require a resource or collection context
org.kde.pim.akonadiserver: Handler exception when handling command FetchItems on connection plasmashell-1310126243 (0x557a8a4d5700) : Operations based on remote identifiers require a resource or collection context
org.kde.pim.akonadiserver: Handler exception when handling command FetchItems on connection plasmashell-1310126243 (0x557a8a4d5700) : Operations based on remote identifiers require a resource or collection context
org.kde.pim.akonadiserver: Handler exception when handling command FetchItems on connection plasmashell-1310126243 (0x557a8a4d5700) : Operations based on remote identifiers require a resource or collection context
```

**Comment by dhruv8sh** [comment]
Looks like an improper installation.

**Comment by IOplus** [comment]
I've tried installing it through the plasma store and also manually, both ways are giving me this issue.

**Comment by IOplus** [comment]
I've just tried installing it on another computer and had the same issue.

Maybe it has something to do with the fact that my fedora installation came with gnome by default. I installed plasma and removed gnome using the guide on fedora's docs. I did that on this other computer that I tested as well, so maybe it has some relation. If that's the case, I don't know how I can fix it.

**Comment by dhruv8sh** [comment]
Ah yes! That could be the issue. Here's a list of dependencies you need to install.
```
plasma5support
plasmacore
kcmutils
kconfig
kirigami
kquickcontrols
qt6-base
```
All of these come normally with a plasma installation. But you can make sure using this.
After you commented, I tested on three different computer running Plasma and none of them crashed.

**Comment by dhruv8sh** [comment]
There is a similar applet by me mentioned in the README. You can try adding that, if that crashes you system too, it should be a problem with your system personally.

**Comment by IOplus** [comment]
> There is a similar applet by me mentioned in the README. You can try adding that, if that crashes you system too, it should be a problem with your system personally.

Yeah, that's the one I'm using for quite some time now. I've been using it since before the release of Ginti. It works perfectly.

**Comment by IOplus** [comment]
> Ah yes! That could be the issue. Here's a list of dependencies you need to install.
> 
> ```
> 
> plasma5support
> 
> plasmacore
> 
> kcmutils
> 
> kconfig
> 
> kirigami
> 
> kquickcontrols
> 
> qt6-base
> 
> ```
> 
> All of these come normally with a plasma installation. But you can make sure using this.
> 
> After you commented, I tested on three different computer running Plasma and none of them crashed.

I'll try it out once I get home, thanks!

**Comment by IOplus** [comment]
> Ah yes! That could be the issue. Here's a list of dependencies you need to install.
> 
> ```
> 
> plasma5support
> 
> plasmacore
> 
> kcmutils
> 
> kconfig
> 
> kirigami
> 
> kquickcontrols
> 
> qt6-base
> 
> ```
> 
> All of these come normally with a plasma installation. But you can make sure using this.

The one dependency missing was kf5-kirigami (kf6-kirigami was installed). It's all working fine now. Thanks!

**Comment by dhruv8sh** [comment]
But it does use KF6 kirigami. That's weird, I'll look into this.

**Comment by CeruleanDerpo** [comment]
still crashes plasma for me
EDIT: if I place it first on the desktop then on a panel it works?

**Comment by dhruv8sh** [comment]
> Can you run `plasmashell --replace`. Add the plasmoid to your desktop after it. And paste the logs it presents after adding it?

Can you paste logs?
