### ISSUE TITLE
Feature request: set the color to the system's accent color

### ISSUE THREAD

**Issue by IOplus** [dhruv8sh/plasma6-desktopindicator-gnome#4]
It would be nice to have a setting for the color to automatically change with the system's accent color.

**Comment by dhruv8sh** [comment]
It does change with the system's accent color, the highlight color specifically.

**Comment by dhruv8sh** [comment]
It uses Kirigami to fetch the color. I feel like there is a big mismatch in your desktop between framework versions. As you mentioned in the other issue KF5 Kirigami was missing as dependency, but it's not possible for an applet to ask for it until specifically mentioned.
I don't know about your distro, but on Arch I would install the entire qt6 and kf6 groups.

**Comment by IOplus** [comment]
I've tried installing `qt6-*` and `kf6-*`, this should cover everything (it did install a bunch of packages), yet the color doesn't change with the accent color.

**Comment by IOplus** [comment]
It was a problem with my configuration in the settings, sorry. `System Settings > Colors & Themes > Plasma Style` was set to "Breeze Light", which doesn't follow the color scheme. Setting it to "Breeze" (the default) fixes it.

**Comment by dhruv8sh** [comment]
I just pushed an update! Update to the latest version to get rid of the remaining bugs.
