### ISSUE TITLE
does not immediately resize correctly

### ISSUE THREAD

**Issue by boredsquirrel** [dhruv8sh/plasma6-desktopindicator-gnome#5]
Awesome awesome addon! It makes workspaces usable!

I was just about creating a few more workspaces. Suddenly the "expand systray" arrow was squeezed behind the clock.

There has to be some broken interaction between the "flexible spacers" and this widget. It would be great if you could check if this widget immediately resizes.

This might be a plasma bug, but
- the widget already squeezed the entire right too far, so that the systray was behind the clock
- the widget itself was already behind the start menu (kickoff) icon, so not defining its new bigger boundaries correctly

Cheers!

**Comment by dhruv8sh** [comment]
Can you share a screenshot so I can get an idea of what exactly happens?

**Comment by boredsquirrel** [comment]
![grafik](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/113100745/2fad0a6c-e098-4841-8d07-b1114ea5ba80)

this is my panel:
- kickoff to the left (app launcher)
- Ginti
- some widgets with constant width
- flexible spacer
- default icons-only taskbar
- flexible spacer
- systray
- clock

This may be a bug in the flexible spacers, as one time they didnt adjust correctly, one time Ginti was partly behind the app launcher icon. One time the "arrow up" in the systray was behind the clock.

But there may be something in Ginti that could be improved, so I report here first

**Comment by dhruv8sh** [comment]
I am very sure it is a problem with the applet. I'll have a look.

**Comment by dhruv8sh** [comment]
Fixed!
