### ISSUE TITLE
Visual bug (wrong vertical position) on the current desktop pill when starting a new plasma session

### ISSUE THREAD

**Issue by sonic-warrior** [dhruv8sh/plasma6-desktopindicator-gnome#6]
Hello, thank you so much for creating this plasmoid. I have a small visual bug every time I start the plasma session. The bug is that the "current virtual desktop pill" vertical position is a little above where it should be in relation to the others pills. But if i switch between virtual desktops, the pill returns to the expected position and everything works as expected.

Before (After starting a new plasma session):
![Captura de tela de 2024-06-11 12-34-04-1](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/43729573/ffaf379c-1425-4c52-9a69-fb5438db1b9a)

After switching virtual desktops:
![Captura de tela de 2024-06-11 12-35-54-1](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/43729573/c33e0b11-e231-452e-89a9-5463f0324c4a)

Info about my desktop
EndeavourOS Linux
KDE Plasma Version: 6.0.5
KDE Frameworks: 6.2.0
Qt Version: 6.7.1
Wayland session 

Sorry if the text sounds strange, english is not my first language.

**Comment by Parth589** [comment]
im having this same issue. Have you found any solution??

**Comment by sonic-warrior** [comment]
@Parth589 not yet. I will take a look at the code to see what is going on.

**Comment by lo-yak** [comment]
Same problem. If someone finds out a workaround, please update! Thanks.

**Comment by dhruv8sh** [comment]
This is very much related to #5. Both of these are not reproducible on my system. [Here](https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/67322047/68249535-bfb4-4834-8467-898aa793e1d8) is the screen recording.

There is an animation played by the panel before it pops up into view. It **could** be that before the animation is played, the X and Y co-ordinates are assigned to the pill. If this is the case I'll try adding a delay before the pills pop into view.

**Comment by sonic-warrior** [comment]
I was thinking it could be this. My pc is very slow so it takes some time to play the animations when i open plasma shell. Here's a recording from my system:


https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/assets/43729573/c51fc9ca-e28d-4f10-8129-00b9232703cc

**Comment by dhruv8sh** [comment]
Should be fixed now! I'll make a release.
